module.exports = {
	arrowParens: "avoid",
	bracketSpacing: true,
	embeddedLanguageFormatting: "auto",
	htmlWhitespaceSensitivity: "css",
	insertPragma: false,
	jsxBracketSameLine: false,
	jsxSingleQuote: false,
	printWidth: 96,
	proseWrap: "preserve",
	quoteProps: "as-needed",
	requirePragma: false,
	semi: false,
	singleQuote: false,
	tabWidth: 2,
	trailingComma: "es5",
	useTabs: true,
	vueIndentScriptAndStyle: false,
	endOfLine: "lf",
}
